# Generated by Django 2.1.7 on 2020-05-03 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='index',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True, db_column='上传时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='bulk_delete_privilege',
            field=models.CharField(blank=True, db_column='批量删除权限', default='无', max_length=255, null=True),
        ),
    ]
