# Generated by Django 2.1.7 on 2019-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolinginfo',
            name='pooling_ratio',
            field=models.FloatField(blank=True, db_column='pooling比例', null=True),
        ),
    ]
