# Generated by Django 2.1.7 on 2019-12-10 12:45

from django.db import migrations, models

import databaseDemo.models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile',
                 models.FileField(db_column='上传文件', null=True, upload_to=databaseDemo.models.user_directory_path)),
                ('uploadUrl', models.CharField(db_column='项目', max_length=255)),
                ('uploadOperator', models.CharField(blank=True, db_column='上传者', max_length=255, null=True)),
            ],
        ),
    ]
