# Generated by Django 2.1.7 on 2019-12-10 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': '上传文件信息表'},
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='上传文件信息表',
        ),
    ]
