# Generated by Django 2.1.7 on 2020-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0002_remove_libraryinfo_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'email_unique': '该邮箱地址已被占用。'}, max_length=254, unique=True,
                                    verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, db_column='昵称', error_messages={'nick_name_unique': '该昵称已被占用。'},
                                   max_length=255, unique=True),
        ),
    ]
