# Generated by Django 2.1.7 on 2019-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0002_poolinginfo_pooling_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencinginfo',
            name='end_time',
            field=models.DateField(blank=True, db_column='下机时间', null=True),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='start_time',
            field=models.DateField(blank=True, db_column='上机时间', null=True),
        ),
    ]
