# Generated by Django 2.1.7 on 2019-12-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0003_auto_20191210_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencinginfo',
            name='poolingLB_id',
            field=models.ForeignKey(blank=True, db_column='pooling号', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='SequencingInfo_CaptureInfo', to='databaseDemo.CaptureInfo',
                                    to_field='poolingLB_id'),
        ),
    ]
