# Generated by Django 2.1.7 on 2019-12-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0004_auto_20191211_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryinfo',
            name='dna_id',
            field=models.ForeignKey(blank=True, db_column='DNA提取编号', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='LibraryInfo_ExtractInfo',
                                    to='databaseDemo.ExtractInfo', to_field='dna_id'),
        ),
        migrations.AlterField(
            model_name='libraryinfo',
            name='sample_id',
            field=models.ForeignKey(blank=True, db_column='样本编号', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='LibraryInfo_ClinicalInfo', to='databaseDemo.ClinicalInfo',
                                    to_field='sample_id'),
        ),
    ]
