# Generated by Django 2.1.7 on 2019-12-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('databaseDemo', '0005_auto_20191217_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalinfo',
            name='category',
            field=models.TextField(blank=True, db_column='癌种', null=True),
        ),
        migrations.AddField(
            model_name='clinicalinfo',
            name='diagnose_others',
            field=models.TextField(blank=True, db_column='诊断备注', null=True),
        ),
        migrations.AddField(
            model_name='clinicalinfo',
            name='stage',
            field=models.TextField(blank=True, db_column='分期', null=True),
        ),
    ]
